require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
require('plugins.mini')
require('plugins.oil')
require('plugins.project')
-- require('plugins.tokyonight')
require('plugins.bluloco')
require('plugins.nvim-treesitter')
