#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# use managed layout favor the existing window
yabai -m config layout                       bsp
yabai -m config window_placement             second_child

# disable auto-balance and use split ratio instead
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# override clear all spaces and allow only gaps
# yabai -m config --space 0 layout float window_gap 4
yabai -m space --gap abs:4

# mouseless window auto focus
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on

# floating windows always on top
yabai -m config window_topmost off

# borders
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# float by default
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."
